server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: jasoncaodev
    password: password
    url: jdbc:postgresql://localhost:5432/customer
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true